tests/test_track_obj: Fix for clang++
clang++ complains if private members are unused, so make them protected.

error: private field 'bar_' is not used [-Werror,-Wunused-private-field]