Revert "tuple tests: Use static_assert() in constexpr tests."
This reverts commit 798210eeaedd88477b71115423b1d7928e81138f.

Because this doesn't work with g++ (at least version 5.2.1)
though it does work with clang++ (3.8).

g++ gives this error:

test_tuple_start.cc: In function ‘constexpr void test_tuple_start_constexpr()’:
test_tuple_start.cc:130:3: error: non-constant condition for static assertion
   static_assert(std::get<0>(t_prefix) == nullptr,
   ^
test_tuple_start.cc:130:3: error: ‘nullptr’ is not a constant expression