test_limit_reference: Avoid virtual-move-assign warning
"= delete" Bases's move operations because the defaulted one
would call non-trivial assignment operators in the virtual bases.

This avoids this compiler warning, at least with g++ 9.2:

test_limit_reference.cc:12:7: error: defaulted move assignment for ‘{anonymous}::Base’ calls a non-trivial move assignment operator for virtual base ‘sigc::trackable’ [-Werror=virtual-move-assign]
   12 | class Base : virtual public sigc::trackable
      |       ^~~~
test_limit_reference.cc:22:7: error: defaulted move assignment for ‘{anonymous}::Derived’ calls a non-trivial move assignment operator for virtual base ‘{anonymous}::Base’ [-Werror=virtual-move-assign]
   22 | class Derived : virtual public Base, public Base2

It would be nice if this test had a comment saying what it is testing.